neo4j:
    uri: bolt://localhost:7687
    user: neo4j
    password: your_password

google_ai_studio:
    api_key: "AIzaSyAte-NzIOs6a4tC7tHn6f5cB_9lqhHg1VQ"
    api_key2: "AIzaSyA4rgeoHntQla-quwzc8sS5vL6yHZZ49m4"
    api_key3: "AIzaSyDQAbWsEhCwy0uSl9gt6PgMBYCfHZFM2tE"
    model: "gemini-1.5-flash-latest" 