version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3.10
    volumes:
      - ..:/workspaces/ran-qa-rag:cached
    command: sleep infinity
    environment:
      - PYTHONUNBUFFERED=1

  neo4j:
    image: neo4j:5
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=neo4j/ranqarag#1
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: